---
# tasks file for prod
- name: install pack
  apt: name={{item}} state=present
  with_items:
    - git
    - maven

- name: copy boxfuse from github
  git: repo={{ rep }} dest={{ dest_folder }}

- name: Compile war file
  shell: "mvn package"
  args: 
   chdir: /usr/myapp
    
