---
# tasks file for web
- name: install tomcat service
  apt:
    name: tomcat8
    state: present
- name: Synchronization war file
  synchronize: src=/usr/myapp/target/hello-1.0.war dest=/var/lib/tomcat8/webapps/
  
